apiVersion: v1
kind: Service
metadata:
  name: common
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: common
    release: __release_tag__
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common
      release: __release_tag__
  template:
    metadata:
      labels:
        app: common
        release: __release_tag__
    spec:
      containers:
        - name: common
          image: '__docker_registry_server__/data.stack:common.__release__'
          ports:
            - containerPort: 3000
          # livenessProbe:
          #   httpGet:
          #     path: /common/health/live
          #     port: 10003
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 60
          # readinessProbe:
          #   httpGet:
          #     path: /common/health/ready
          #     port: 10003
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 60
          envFrom:
          - configMapRef:
              name: config
      imagePullSecrets:
        - name: regsecret        

